export const CHANGE_CATEGORY="CHANGE_CATEGORY"
export const GET_CATEGORY_SUCCESS="GET_CATEGORY_SUCCESS"

export const CHANGE_PRODUCTS="CHANGE_PRODUCTS"
export const GET_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS"
export const CREATE_NEW_PRODUCT="CREATE_NEW_PRODUCT"
export const UPDATE_NEW_PRODUCT="UPDATE_NEW_PRODUCT"

export const ADD_TO_CART="ADD_TO_CART"
export const REMOVE_FROM_CART="REMOVE_FROM_CART"
